version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - ./data:/app/data
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: npx nx serve backend

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: dockerfile
  #   ports:
  #     - "4200:4200"
  #   volumes:
  #     - ./:/app
  #     - node_modules:/app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #   command: npx nx serve frontend
  #   depends_on:
  #     - backend

volumes:
  sqlite_data:
    driver: local
  node_modules: